### ISSUE TITLE
Move code style pages to this repository

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Guidelines#1]
The pages to move: https://github.com/Polyjuice/Polyjuice/wiki/Coding-Style.

Original issue: https://github.com/Starcounter/CompanyTrack/issues/184.

**Comment by warpech** [comment]
Thanks for taking this!

**Comment by miyconst** [comment]
There are quite a few pages, plain md files without table of content is not a very useful resource.

How about using GitHub WiKi or setup another GitBook?

**Comment by warpech** [comment]
I think GitBook is a great idea. 

For the moved pages, please replace the content in https://github.com/polyjuice/polyjuice/wiki with a link to the new location.

**Comment by miyconst** [comment]
Moved.

All Polyjuice WiKi pages are marked as `The page has been moved to GitBook.`
