### ISSUE TITLE
The src folder in solution

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Guidelines#3]
Long time ago it was decided to put source files into a `src` folder as described here: https://starcounter.gitbooks.io/guidelines/content/project_structure.html.

In practice it's not always convenient to add the folder and I am thinking of removing it. In the same time we have the `tests` folder which plays nice.

So, the question is should we keep the `src` and `tests` folders?

cc @warpech, @andwah, @alemoi, @chrhol, @per-samuelsson, @aloscha, @ubbeK

**Comment by warpech** [comment]
I got used to having `src` and `test` folders, which goes in line with DNX projects structure (e.g. https://github.com/aspnet/StaticFiles/).

My opinion is that we don't have to break all habits of C# developers. If they have a habit of having `src` and `test` directories, lets follow that.

**Comment by warpech** [comment]
> goes in line with DNX projects structure

The DNX pattern isn't just to have `src` and `test`, but actually `src/<name of the project>` and `test/<name of the test project>`, which is acutally useful for me here:

- https://github.com/StarcounterPrefabs/Launcher/tree/master/src/Launcher
- https://github.com/StarcounterPrefabs/Launcher/tree/master/test/Launcher_AcceptanceTest
- https://github.com/StarcounterPrefabs/Launcher/tree/master/test/Launcher_AcceptanceHelperOne
- https://github.com/StarcounterPrefabs/Launcher/tree/master/test/Launcher_AcceptanceHelperTwo

This is Launcher app, Launcher test, and two helper apps for testing.

**Comment by per-samuelsson** [comment]
> My opinion is that we don't have to break all habits of C# developers. If they have a habit of having `src` and `test` directories, lets follow that.

+1 on that.

> I guess that @Starcounter-jack would prefer just 3 files on the repo root level.

He'll have to answer for himself, but I guess its not like that. In a *repo* root, you usually have more, like at least `gitignore` and possibly a project file. I think what @Starcounter-jack favor (and where I agree) is we should keep it simple (i.e. 3 files) once we are *in* the project root / src folder.

**Comment by miyconst** [comment]
>I got used to having src and test folders, which goes in line with DNX projects structure (e.g. https://github.com/aspnet/StaticFiles/).

I remember quite a few people were unhappy about the `src` folder in the very beginning, that is why I rose the question again.

Looks like we don't have any strong "against", let's keep the folder and the structure we agreed on before.

The most important: **let's follow our own instructions**.

Closing the issue. Everyone feel free to reopen it if needed.

**Comment by warpech** [comment]
> I think what @Starcounter-jack favor (and where I agree) is we should keep it simple (i.e. 3 files) once we are in the project root / src folder.

Actually I think I remember him saying exactly that. Perfect, then all seem to vote for `src` and `test`. That's something!
