### ISSUE TITLE
Adopt .NET Core coding style for C#

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Guidelines#5]
As discussed in https://github.com/StarcounterPrefabs/Images/pull/64#discussion_r95549918, I think that we should extend the page [csharp_code_formatting.md](https://github.com/StarcounterPrefabs/Guidelines/blob/master/coding_style/csharp_code_formatting.md) to reference the .NET Core coding style for C# and suggest adopting all principles from it: 

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Anyone has something against it?

cc @aloscha, @miyconst, @mmnosek, @joozek78, @ubbeK, @diliger, @Joltrix

**Comment by ubbeK** [comment]
Overall I think it is a good idea but I don't agree with number 6 for instance, 

> Namespace imports should be specified at the top of the file, outside of namespace declarations and should be sorted alphabetically.

**Comment by joozek78** [comment]
I always ignore imports anyway. IDE takes care of them and no human should
worry about them (apart from rare cases)

**Comment by mmnosek** [comment]
For me, it also doesn't make any sense. Sorting namespaces is a waste of time if I need to do that manually.

**Comment by warpech** [comment]
@ubbeK What do you think of order sorting then? I think that it does not matter much.

The "other" Microsoft guidelines (for ASP.NET) does not mention sorting it at all: https://github.com/aspnet/Home/wiki/Engineering-guidelines#coding-guidelines

**Comment by miyconst** [comment]
>3. Prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`.

Very disagree. The `_` is an evil. C# is a language after all, and that means a human should be able to read it. Try to read the following and you will see which one is more "readable".

```cs
_name = name;
this.Name = name;
```

>6. ... and should be sorted alphabetically.

Disagree. First it should be sorted by category. [System, Framework, Third party libraries, Own libraries, Own projects, Current project namespaces].

------

Everything else looks good.

**Comment by ubbeK** [comment]
I agree with @miyconst regarding sort by category

**Comment by warpech** [comment]
> 3. Prefix instance fields with _, static fields with s_ and thread static fields with t_.

@miyconst since in Starcounter.Core we need to switch from fields to properties, it should not matter that much actually. Before that, I agree this is not applicable to us.

**Comment by warpech** [comment]
So I will write on that page that we adopt .NET Core rules with the following changes:

- Point 3 is removed. Write fields in `PascalCase` just like other class members.
- Point 4 is removed. Verbose `this.` is better because it emphasizes that you mean a class member.
- Point 6 is changed: sort Usings like explained by Konstantin.
- We understand point 10 that we only use `var` in a line that calls a constructor.

Any final comments?

**Comment by joozek78** [comment]
> We understand point 10 that we only use var in a line that calls a constructor.

I totally disagree - usage of `var` makes the code more readable (and easier to write) because it lets one omit information that is often unnecessary. The cases where it's important to explicitly state the type are rare

**Comment by aloscha** [comment]
I agree with @joozek78.
Sometimes `var` refers directly not to constructor but to obvious type. http://stackoverflow.com/questions/737835/resharper-and-var

**Comment by miyconst** [comment]
>Point 3 is removed. Write fields in PascalCase just like other class members.

Did you mean public fields or all fields?

>Point 6 is changed: sort Usings like explained by Konstantin.

Note: this is just my preference, but if it causes inconvenience for other team members, I do not insist. Also I never care about alphabetical sort, not in whole section and not in a "category" of usings.

>We understand point 10 that we only use `var` in a line that calls a constructor.

+1 from me.

**Comment by warpech** [comment]
> I totally disagree - usage of `var` makes the code more readable (and easier to write) because it lets one omit information that is often unnecessary. The cases where it's important to explicitly state the type are rare.

Let's only focus on the "readable" part. Making software is 95% reading, and 5% writing, so let's optimize reading.

With **implicit** types (`var`) you need to put the mouse over the right side of the `=` sign in your IDE to know the type. This is 2 seconds distraction. When you press F12 just to check the type, it is a 10 seconds distraction. And maybe even 10 minutes, because you start wondering about the things you were not supposed to dive into.

With **explicit** types in your code, you can paste a fragment of the code in a GitHub issue or documentation, with less need for explaining what does it do. I think that this is important in our case.

There are just dozens of opinions both pro and con: https://www.infoq.com/news/2008/05/CSharp-var

This article lists drawbacks of `var` that I agree with: http://www.brad-smith.info/blog/archives/336

**Comment by warpech** [comment]
> Did you mean public fields or all fields?

I mean all fields. Is this wrong?

**Comment by warpech** [comment]
I have rewritten the page to consider all the advice gathered here: https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html

Comments are welcome.

Whatever is published at this page, should be our standard way of writing code in Starcounter apps from now on.

**Comment by warpech** [comment]
Based on suggestions from @joozek78 and @mmnosek, I have changed from:

> Use implicit type (`var`) on lines that call the constructor. Otherwise, always use explicit type. This is a little bit verbose, but has benefits in readability without knowing the context.

To: 

> Use implicit type (`var`) on lines that call a constructor, a generic method, a factory method or the type is otherwise obvious from the context (e.g. `var person = Db.SQL<Person>("SELECT p FROM Person p").First`). Otherwise, it is preferred to use explicit type (e.g. `DateTime expiration = GetDefaultExpiration<SystemUserSession>()`)

**Comment by aloscha** [comment]
Accept from me :)

**Comment by aloscha** [comment]
@warpech we really want to stay with underscore?
`We use _camelCase for internal and private fields and use readonly where possible.`

**Comment by miyconst** [comment]
>> Did you mean public fields or all fields?

>I mean all fields. Is this wrong?

Nothing wrong with it, just I was using different style, have to adjust to the new version.

**Comment by miyconst** [comment]
Everything except `_` looks good for me. I would really like to rid off any `_`.

**Comment by warpech** [comment]
> We use _camelCase for internal and private fields and use readonly where possible.

@aloscha where do you see that? It is not on the page https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html. 

Are you referring to the external documents? They were just the basis. What is important to us is the rules in our Guidelines Gitbook.

> Everything except `_` looks good for me. I would really like to rid off any `_`.

I have removed the last `_` from the page.

**Comment by warpech** [comment]
Closing this issue. Of course it is still welcome that we discuss the Guidelines - in that case, please open a new specific issue.
 
Thanks a 💯 for your collaboration on this!
