### ISSUE TITLE
Changes to the project structure

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Guidelines#7]
I would like to propose changes to the desired project structure (https://starcounter.gitbooks.io/guidelines/content/project_structure.html):

1. the `bin` directory should be inside `src/<appname>`, because when the repo has multiple apps, the binaries and DLLs should not mix
2. the `tests` directory should be renamed to `test` because that's the convention ([see](https://github.com/aspnet/Mvc))
3. remove `project.json` file, because it is and will not be used (.Net is switching away from it)

@miyconst, @Mackiovello, @joozek78, @mmnosek, @aloscha, @ubbeK, @Joltrix, @diliger any comments? 

I would like to adopt this project structure soon in all apps, because then we can have automated builds that use the same template.

**Comment by warpech** [comment]
cc @KmaTTi89

**Comment by miyconst** [comment]
I am fine with it, and actually already use those new terms :)

**Comment by mmnosek** [comment]
Looks very good to me.

Should those rules be also adopted to existing customer's projects? Or just in Prefabs and Samples, and in any of new projects we will start?

**Comment by warpech** [comment]
The customers often ask us for proposed framework for large projects. I think that this is part of what we can propose as the answer to this question. But actually since the customers own their projects, the final word belongs to them.

If they don't agree with this, still it is worth listening why exactly.

**Comment by warpech** [comment]
Applied in https://starcounter.gitbooks.io/guidelines/content/project_structure.html
